[package]
name = "rmx-mg"
version = "0.1.0"
authors = ["ruescasd <fastness@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.11"
rand_core = "0.5.0"
rand = "0.7.3"
curve25519-dalek = {version = "3.0.0", features = ["serde"]}
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }